import { GoogleGenAI, Type } from "@google/genai";
import { AnalyzedElement, AspectRatio } from "../types";

/**
 * N.I.M's Core Magic Service
 */
const ai = new GoogleGenAI({ apiKey: process.env.API_KEY || '' });

/**
 * Analyzes an image to identify distinct elements for the "Magic Wand" simulation.
 */
export const analyzeImageContents = async (base64Image: string): Promise<AnalyzedElement[]> => {
  const cleanBase64 = base64Image.replace(/^data:image\/(png|jpeg|jpg|webp);base64,/, '');

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-lite-latest', // Fast and reliable for vision analysis
      contents: [
        {
          parts: [
            { inlineData: { mimeType: 'image/jpeg', data: cleanBase64 } },
            { text: 'Analyze this image or document. List the main visual subjects, text blocks, and objects that could be extracted and recomposed into a new scene. Return as JSON.' }
          ]
        }
      ],
      config: {
        responseMimeType: 'application/json',
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            elements: {
              type: Type.ARRAY,
              items: {
                type: Type.OBJECT,
                properties: {
                  label: { type: Type.STRING },
                  type: { type: Type.STRING, enum: ['object', 'text', 'background', 'person'] },
                  description: { type: Type.STRING }
                },
                required: ['label', 'type', 'description']
              }
            }
          }
        }
      }
    });

    const result = JSON.parse(response.text || '{"elements": []}');
    
    return result.elements.map((el: any, index: number) => ({
      id: `el-${index}`,
      label: el.label,
      type: el.type,
      selected: el.type !== 'background'
    }));

  } catch (error) {
    console.error("N.I.M's Analysis failed:", error);
    return [{ id: '1', label: 'Main Subject', type: 'person', selected: true }];
  }
};

/**
 * Generates the recomposed image using the portrait reference.
 */
export const generateRecomposedImage = async (
  originalImageBase64: string,
  selectedElements: AnalyzedElement[],
  aspectRatio: AspectRatio,
  templatePrompt: string,
  customPrompt?: string
): Promise<string> => {
  const cleanBase64 = originalImageBase64.replace(/^data:image\/(png|jpeg|jpg|webp);base64,/, '');
  const keptItems = selectedElements.filter(e => e.selected).map(e => e.label).join(", ");
  
  const prompt = `
    Task: Recompose visual elements from the provided portrait source into a new cinematic landscape.
    Keep these subjects: ${keptItems}.
    Environmental Style: ${templatePrompt}.
    Custom Instructions: ${customPrompt || 'Create a balanced, high-resolution 1080p-style composition.'}
    Ensure subjects maintain their likeness but fit naturally into the new wide orientation.
  `;

  try {
    // Use gemini-2.5-flash-image for standard high-quality generation
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: [
        {
          parts: [
            { inlineData: { mimeType: 'image/jpeg', data: cleanBase64 } },
            { text: prompt }
          ]
        }
      ],
      config: {
        imageConfig: {
          aspectRatio: aspectRatio as any
        }
      }
    });

    for (const part of response.candidates?.[0]?.content?.parts || []) {
      if (part.inlineData) {
        return `data:image/png;base64,${part.inlineData.data}`;
      }
    }
    throw new Error("No image data generated by the server.");

  } catch (error) {
    console.error("N.I.M's Generation failed:", error);
    throw error;
  }
};

/**
 * Generates a completely new image from scratch.
 */
export const generateNewImage = async (prompt: string, aspectRatio: AspectRatio): Promise<string> => {
  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: [{ parts: [{ text: prompt }] }],
      config: {
        imageConfig: {
          aspectRatio: aspectRatio as any
        }
      }
    });

    for (const part of response.candidates?.[0]?.content?.parts || []) {
      if (part.inlineData) {
        return `data:image/png;base64,${part.inlineData.data}`;
      }
    }
    throw new Error("Empty response from magic server.");
  } catch (error) {
    console.error("N.I.M's New image generation failed:", error);
    throw error;
  }
};